version: '2.2'
services:
  emitendbhost:
    image: mongo
    ports:
      - "27018:27017"
  redishost:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .
    ports: 
      - "3001:3001"
    command: nodemon ./bin/www
    depends_on:
      - emitendbhost
    volumes:
      - .:/app/
      - /app/node_modules/
    environment:
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - SECRET_TOKEN
      - ACTIVE_LOGIN
      - ACTIVE_TOKEN_H
      - ROOT_FOLDER_UPLOAD
      - REDIS_HOST
      - REDIS_PORT