version: '2.2'
services:
  emailsenderdbhost:
    image: mongo
    command: [--auth]
    ports:
      - "27017"
  emailsenderredishost:
    image: redis
    ports:
      - "6379"
  emailsender:
    build: .
    ports: 
      - "3002:3002"
    depends_on:
      - emailsenderdbhost
    volumes:
      - .:/app/emiten/
      - /app/emiten/node_modules/
    environment:
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - SECRET_TOKEN
      - ACTIVE_LOGIN
      - ACTIVE_TOKEN_H
      - ROOT_FOLDER_UPLOAD